### PR TITLE
Support for webhook url instead of company name and token.

### PR DESCRIPTION
**Pull request by rafaelgaspar**
Support for the new webhook URL form instead of company name and token.

### CODE REVIEW

**Comment by rafaelgaspar** [comment]
Fixes #3

**Comment by esanchezm** [comment]
Thanks again. Could you please update the README file to document it? Actually, if this is the new method, feel free to remove the deprectated way.

**Comment by rafaelgaspar** [comment]
The old way will still work for awhile as far as I know, so it's best to keep it backwards compatible until slack team removes this.

I'll update the README.

**Comment by rafaelgaspar** [comment]
Rebased with current master and changed README.

**Comment by esanchezm** [comment]
Sorry, I didn't mean to remove the code, but the documentation regarding the old system, which is exactly what you did :)

**Pull request merged**
